# Generated by Django 3.2.7 on 2021-09-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=50, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('delivery', models.CharField(choices=[('Pick Up', 'Pick Up'), ('Home Delivery', 'Home Delivery')], max_length=50, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
